// Package launch builds and runs the multiplexer command that opens an omp
// covibe session in a tab/window. It is shared by the `covibe start` CLI and
// the dashboard's web-initiated session creation so both take the exact same
// path.
package launch

import (
	"fmt"
	"os"
	"time"

	"github.com/lassulus/covibe/internal/mux"
)

// Options describes a session to launch.
type Options struct {
	Self       string // covibe executable path (resolved from os.Executable if empty)
	ID         string // stable session id (generated by the wrapper if empty)
	Name       string
	Dir        string
	Mux        string // "zellij" | "tmux"
	MuxSession string
	RelayHost  string // public host for guest links, e.g. "covibe.lassul.us"
	WebClient  string // collab-web base for browser links, e.g. "https://my.omp.sh"
	LocalRelay string // ws(s):// base the omp host connects to
	Omp        string
	StateDir   string
	Model      string // omp --model (optional; may carry :thinking suffix)
	Thinking   string // omp --thinking level (optional)
}

// inner builds the `covibe session ...` argv that the mux runs in the pane.
func (o Options) inner(id, sess string) ([]string, error) {
	self := o.Self
	if self == "" {
		exe, err := os.Executable()
		if err != nil {
			return nil, err
		}
		self = exe
	}
	omp := o.Omp
	if omp == "" {
		omp = "omp"
	}
	argv := []string{
		self, "session",
		"--name", o.Name,
		"--dir", o.Dir,
		"--omp", omp,
		"--mux", o.Mux,
		"--mux-session", sess,
	}
	if o.RelayHost != "" {
		argv = append(argv, "--relay-host", o.RelayHost)
	}
	if o.WebClient != "" {
		argv = append(argv, "--web-client", o.WebClient)
	}
	if o.LocalRelay != "" {
		argv = append(argv, "--local-relay", o.LocalRelay)
	}
	if o.StateDir != "" {
		argv = append(argv, "--state-dir", o.StateDir)
	}
	if o.Model != "" {
		argv = append(argv, "--model", o.Model)
	}
	if o.Thinking != "" {
		argv = append(argv, "--thinking", o.Thinking)
	}
	argv = append(argv, "--id", id)
	return argv, nil
}

func (o Options) spec() (mux.Launcher, mux.Spec, string, error) {
	l, err := mux.For(o.Mux)
	if err != nil {
		return nil, mux.Spec{}, "", err
	}
	id, sess := o.resolveSession()
	inner, err := o.inner(id, sess)
	if err != nil {
		return nil, mux.Spec{}, "", err
	}
	return l, mux.Spec{Name: o.Name, Dir: o.Dir, Session: sess, InnerArgv: inner}, sess, nil
}

// resolveSession fills a stable id (generating one when empty) and the derived
// per-session mux session name.
func (o Options) resolveSession() (id, sess string) {
	id = o.ID
	if id == "" {
		id = fmt.Sprintf("%d-%d", time.Now().UnixNano(), os.Getpid())
	}
	return id, mux.SessionName(o.MuxSession, o.Name, id)
}

// Command returns the multiplexer argv without running it (dry-run).
func Command(o Options) ([]string, error) {
	l, spec, _, err := o.spec()
	if err != nil {
		return nil, err
	}
	return l.Command(spec)
}

// Launch ensures the (per-session) multiplexer session exists, then opens it.
func Launch(o Options) (string, error) {
	l, spec, sess, err := o.spec()
	if err != nil {
		return "", err
	}
	if err := l.Ensure(sess); err != nil {
		return sess, err
	}
	return sess, l.Launch(spec)
}
